/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyphongkham.view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import quanlyphongkham.bus.UserBUS;
import quanlyphongkham.dto.UserDTO;

/**
 *
 * @author ADMIN
 */
public class JPanelThongTinTaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form JPanelThongTinTaiKhoan
     */
    private ResultSet rs;
    private UserBUS userBUS;
    private String manv;
    private UserDTO udto;
   
    public JPanelThongTinTaiKhoan() {
        initComponents();
        rs = null;
        userBUS = new UserBUS();
        rs = userBUS.loadDuLieuThongTinNV("nv001");
        loadThongTin();
    }
    public JPanelThongTinTaiKhoan(UserDTO udto) {
        initComponents();
        rs = null;
        userBUS = new UserBUS();
        this.udto=udto;
        rs = userBUS.loadDuLieuThongTinNV(udto.getMaNV());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                loadThongTin();
            }
        });        
    }
    
    private void loadThongTin() {
        try {
            rs.next();
            txt_manv.setText(rs.getString("manv"));
            txt_hoten.setText(rs.getString("hoten"));
            txt_gioitinh.setText(rs.getString("gioitinh"));
            txt_ngaysinh.setText(rs.getString("ngaysinh"));
            txt_chucvu.setText(rs.getString("chucvu"));
            txt_diachi.setText(rs.getString("diachi"));
            txt_matkhau.setText(rs.getString("matkhau"));

            txt_sdt.setText(rs.getString("matkhau"));
            txt_taikhoan.setText(rs.getString("taikhoan"));
            txt_quyenhan.setText(rs.getString("tenquyenhan"));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_diachi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_taikhoan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_matkhau = new javax.swing.JTextField();
        txt_ngaysinh = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_manv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_gioitinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_chucvu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_quyenhan = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("SĐT:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel11.setText("Quyền Hạn:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 60, -1));

        txt_diachi.setEditable(false);
        add(txt_diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 170, -1));

        jLabel8.setText("Địa Chỉ:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        txt_taikhoan.setEditable(false);
        add(txt_taikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 170, -1));

        jLabel9.setText("Tài Khoản:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        txt_matkhau.setEditable(false);
        add(txt_matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 170, -1));

        txt_ngaysinh.setEditable(false);
        txt_ngaysinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ngaysinhActionPerformed(evt);
            }
        });
        add(txt_ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 170, -1));

        txt_sdt.setEditable(false);
        add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 169, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông Tin Tài Khoản");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel2.setText("Mã Nhân Viên:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        txt_manv.setEditable(false);
        txt_manv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_manvActionPerformed(evt);
            }
        });
        add(txt_manv, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, -1));

        jLabel3.setText("Chức Vụ:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        txt_gioitinh.setEditable(false);
        add(txt_gioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 50, -1));

        jLabel4.setText("Họ Và Tên Nhân Viên:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        txt_hoten.setEditable(false);
        add(txt_hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 170, -1));

        jLabel5.setText("Ngày Sinh:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        txt_chucvu.setEditable(false);
        add(txt_chucvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 170, -1));

        jLabel10.setText("Mật Khẩu:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jLabel6.setText("Giới Tính:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        txt_quyenhan.setEditable(false);
        add(txt_quyenhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ngaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ngaysinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ngaysinhActionPerformed

    private void txt_manvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_manvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_manvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_chucvu;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_gioitinh;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_manv;
    private javax.swing.JTextField txt_matkhau;
    private javax.swing.JTextField txt_ngaysinh;
    private javax.swing.JTextField txt_quyenhan;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_taikhoan;
    // End of variables declaration//GEN-END:variables
}
